[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "16"

[context.deploy-preview.environment]
  NODE_VERSION = "16"

[context.branch-deploy.environment]
  NODE_VERSION = "16"
